### ISSUE TITLE
Failed connection attempts should be removed from pool

### ISSUE THREAD

**Issue by bergey** [nikita-volkov/hasql-pool#1]
`hasql-pool` keeps the results of failed connection attempts in the pool, and offers them to subsequent queries.  In consequence, transient connection failures at program start poison the pool, and all future attempts at running SQL fail.

If I understand correctly, [resource-pool](https://hackage.haskell.org/package/resource-pool-0.2.3.2/docs/Data-Pool.html) expects `create` to return a valid resource or throw an exception.  If `create` or subsequent actions using the resource throw an exception, `resource-pool` removes the resource from the pool, making room for a new connection.

`hasql-pool` encodes connection failures as `Left`, which remain in the pool, and are never replaced by actual connections.

**Comment by domenkozar** [comment]
FYI: this was solved in https://github.com/nikita-volkov/hasql-pool/pull/3/files and then re-implemented in further commits. Released in 0.5.0.1

**Comment by nikita-volkov** [comment]
Somehow missed the issue. Thanks for reporting and responding guys!
