### ISSUE TITLE
Switch from microseconds to seconds as unit for timeout

### ISSUE THREAD

**Issue by nikita-volkov** [nikita-volkov/hasql-pool#24]
I can't imagine a case where one would need a resolution higher than second for timeout.

@robx what do you think?

**Comment by robx** [comment]
I don't that's a particularly good idea, I wouldn't want to restrict the API arbitrarily.

E.g. one might well want lower timeouts when writing tests.

I guess the benefit would be less `1000000`s in code? How about if we pass the timeout as a nice duration type, I suppose the default there would be `Data.Time.NominalDiffTime`?

**Comment by nikita-volkov** [comment]
`DiffTime` should be better. But okay I get it. We can leave it as is for now.

**Comment by shinzui** [comment]
Can we reopen the issue? Dealing with microseconds is a little cumbersome. I second the idea of using `Data.Time.NominalDiffTime`.
