### ISSUE TITLE
Extend configuration with a timeout of connection being idle

### ISSUE THREAD

**Issue by nikita-volkov** [nikita-volkov/hasql-pool#29]
Discussion of this is initiated in #28.

**Comment by robx** [comment]
Just to note that with #28, this should be straightforward to implement now (but it's probably also no longer that pressing):

- add `connUseTimeNSec` next to `connCreationTimeNSec`, `poolMaxIdleTime` next to `poolMaxLifetime`
- add a check involving these to `isAlive`
- update `connUseTimeNSec` in `use`'s `onConn`

(and a test :))
