### ISSUE TITLE
hasql-pool

### ISSUE THREAD

**Issue by luss** [nikita-volkov/hasql-pool#36]
I've been compilng and building POSTGREST for a few months on ARM64.   From versions 11.0.0 on it now longer builds on ARM64 and throws this error.  Any thoughts?

HEAD is now at 4197d2f7 bump version to 11.0.1
hasql-pool         > configure
hasql-pool         > Configuring hasql-pool-0.9...
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../haskeline-0.8.2/libHShaskeline-0.8.2-ghc9.2.5.so)
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../ghc-9.2.5/libHSghc-9.2.5-ghc9.2.5.so)
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../terminfo-0.4.1.5/libHSterminfo-0.4.1.5-ghc9.2.5.so)
hasql-pool         > build
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc-pkg: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc-pkg)
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc-pkg: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../terminfo-0.4.1.5/libHSterminfo-0.4.1.5-ghc9.2.5.so)
hasql-pool         > Preprocessing library for hasql-pool-0.9..
hasql-pool         > Building library for hasql-pool-0.9..
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../haskeline-0.8.2/libHShaskeline-0.8.2-ghc9.2.5.so)
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../ghc-9.2.5/libHSghc-9.2.5-ghc9.2.5.so)
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../terminfo-0.4.1.5/libHSterminfo-0.4.1.5-ghc9.2.5.so)
hasql-pool         > [1 of 2] Compiling Hasql.Pool.Prelude
hasql-pool         > [2 of 2] Compiling Hasql.Pool
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../haskeline-0.8.2/libHShaskeline-0.8.2-ghc9.2.5.so)
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../ghc-9.2.5/libHSghc-9.2.5-ghc9.2.5.so)
hasql-pool         > /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/ghc: /lib64/libtinfo.so.6: no version information available (required by /home/rocky/.stack/programs/aarch64-linux/ghc-tinfo6-9.2.5/lib/ghc-9.2.5/bin/../terminfo-0.4.1.5/libHSterminfo-0.4.1.5-ghc9.2.5.so)
hasql-pool         > /usr/bin/ld.gold: error: cannot find -lpq
hasql-pool         > collect2: error: ld returned 1 exit status
hasql-pool         > `gcc' failed in phase `Linker'. (Exit code: 1)
Progress 1/3

Error: [S-7282]
       Stack failed to execute the build plan.

       While executing the build plan, Stack encountered the following errors:

       [S-7011]
       While building package hasql-pool-0.9 (scroll up to its section to see the error) using:
       /home/rocky/.stack/setup-exe-cache/aarch64-linux-tinfo6/Cabal-simple_SvXsv1f__3.6.3.0_ghc-9.2.5 --verbose=1 --builddir=.stack-work/dist/aarch64-linux-tinfo6/Cabal-3.6.3.0 build --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1

**Comment by nikita-volkov** [comment]
It's possible  that the linker fails to find "libpq", which is a part of any postgres distribution.

```
hasql-pool > /usr/bin/ld.gold: error: cannot find -lpq
```

**Comment by luss** [comment]
Thanks, I missed that line in the error messages.  That is likely it.
