### ISSUE TITLE
Nixpkgs build is broken because the test suites are not fixed in latest release

### ISSUE THREAD

**Issue by chrislf** [nikita-volkov/hasql-pool#7]
Would it be possible to make a new release with the fixed test suites included? Nixpkgs pulls by release and the test suites in 0.5.1 are broken, so the package is marked broken in nixpkgs-unstable since last year.

Thank you!

**Comment by nikita-volkov** [comment]
Done!

**Comment by chrislf** [comment]
Thank you!
